(()=>{
'use strict';
const library=document.getElementById('library'),status=document.getElementById('status'),play=document.getElementById('play'),speed=document.getElementById('speed');
const entries=[],byCanvas=new WeakMap();
let playing=true,elapsed=0,last=0;
function draw(entry,frame){const a=entry.action;entry.ctx.clearRect(0,0,a.cellWidth,a.cellHeight);entry.ctx.drawImage(entry.image,(frame%a.columns)*a.cellWidth,Math.floor(frame/a.columns)*a.cellHeight,a.cellWidth,a.cellHeight,0,0,a.cellWidth,a.cellHeight);entry.frame=frame;entry.canvas.dataset.frame=String(frame+1);}
const observer=new IntersectionObserver(changes=>{for(const change of changes){const entry=byCanvas.get(change.target);entry.visible=change.isIntersecting;if(entry.visible&&!entry.image&&!entry.loading){entry.loading=true;const image=new Image();image.src=entry.action.sheet;image.decode().then(()=>{entry.loading=false;if(!entry.visible)return;entry.image=image;entry.error.textContent='';draw(entry,Math.floor(elapsed*entry.fps/1000)%entry.action.frames);}).catch(()=>{entry.loading=false;entry.error.textContent='载入失败，请刷新';});}else if(!entry.visible){entry.image=null;}}},{rootMargin:'160px'});
function tick(time){if(last&&playing&&!document.hidden)elapsed+=(time-last)*Number(speed.value);last=time;for(const entry of entries){if(!entry.visible||!entry.image)continue;const frame=Math.floor(elapsed*entry.fps/1000)%entry.action.frames;if(frame!==entry.frame)draw(entry,frame);}requestAnimationFrame(tick);}
play.addEventListener('click',()=>{playing=!playing;play.textContent=playing?'全部暂停':'全部播放';play.setAttribute('aria-pressed',String(!playing));});
document.addEventListener('visibilitychange',()=>{last=0;});
function renderForm(form){const section=document.createElement('section'),heading=document.createElement('h2'),count=document.createElement('span'),grid=document.createElement('div');heading.textContent=form.name;count.textContent=`${form.actions.length} 个动作与方向`;heading.append(count);grid.className='cards';section.append(heading,grid);library.append(section);
const actions=[...form.actions].sort((a,b)=>(a.category==='direction')-(b.category==='direction'));
actions.forEach((a,index)=>{const card=document.createElement('article'),stage=document.createElement('div'),canvas=document.createElement('canvas'),caption=document.createElement('div'),title=document.createElement('h3'),number=document.createElement('span'),detail=document.createElement('p'),error=document.createElement('span');const id=(form.id==='super'?'L':'N')+String(index+1).padStart(2,'0');card.className='card';card.id=id;stage.className='stage';caption.className='caption';number.className='number';number.textContent=id;title.append(number,document.createTextNode(a.name));detail.textContent=`${a.id} · ${a.frames} 帧`;canvas.width=a.cellWidth;canvas.height=a.cellHeight;canvas.setAttribute('role','img');canvas.setAttribute('aria-label',`${id} ${form.name} ${a.name}，循环动画`);error.className='error';error.setAttribute('role','status');stage.append(canvas,error);caption.append(title,detail);card.append(stage,caption);grid.append(card);const entry={action:a,canvas,ctx:canvas.getContext('2d'),fps:a.fps||form.fps,image:null,visible:false,loading:false,frame:-1,error};entries.push(entry);byCanvas.set(canvas,entry);observer.observe(canvas);});}
async function init(){try{const response=await fetch('assets/ram-library/manifest.json');if(!response.ok)throw Error('manifest');const data=await response.json();data.forms.filter(f=>['super','nono'].includes(f.id)).forEach(renderForm);status.textContent='';}catch{status.textContent='动作资料暂时无法读取，请刷新。';}}
init();requestAnimationFrame(tick);
})();
